### ISSUE TITLE
does not start PIDTuningTool

### ISSUE THREAD

**Issue by lonelymyp** [misan/dcservo#13]
some problem with the port. how to set the port manually?
![default](https://cloud.githubusercontent.com/assets/2085051/20041747/e27c1cec-a47e-11e6-8c97-da878f6b7b4c.jpg)

**Comment by misan** [comment]
Yes, please try with 1 instead of 3 (I have not found a better method that
would work everytime on every computer).

**Comment by lonelymyp** [comment]
Well, it works. Thank you!

**Comment by misan** [comment]
Excellent. Thank you.
