### ISSUE TITLE
Wifi Communication

### ISSUE THREAD

**Issue by PierreAuge** [misan/dcservo#25]
Migel,

What protocol are you using to communicate with the ESP8266 wifi variant? I thought it was UDP but that's not working via netcat. I'm really baffled here. 

Ok for more clarity, I'm using a nodemcu board. The serial output is fine, logs on to network and spits out an IP address, but udp connection just hangs.

Pierre

**Comment by misan** [comment]
I guess you already figured out I was using TCP here.
