### ISSUE TITLE
Pro Micro pin reassignment?

### ISSUE THREAD

**Issue by paukstelis** [misan/dcservo#54]
Bit of a noob question: I want to free up pins 2 and 3 on the Pro Micro for I2C. If I put encoder interrupts on Pin 1 and Pin 7, what would need to change in encoderInt function? Port manipulations scare me.

**Comment by paukstelis** [comment]
Hmm, according to the sparkfun page, ProMicro has 5 external interrupts. Shouldn't it be possible to just swap them? Is this accurate?:

> "The Pro Micro has five external interrupts, which allow you to instantly trigger a function when a pin goes either high or low (or both). If you attach an interrupt to an interrupt-enabled pin, you’ll need to know the specific interrupt that pin triggers: pin 3 maps to interrupt 0, pin 2 is interrupt 1, pin 0 is interrupt 2, pin 1 is  interrupt 3, and pin 7 is interrupt 4."

**Comment by misan** [comment]
That is correct but they do not use the term INT4 or INT5

![image](https://user-images.githubusercontent.com/466120/46096718-344ad080-c1c0-11e8-81d0-490b1470cffd.png)

**Comment by misan** [comment]
And yes, they can be changed, just remember to update any PIN* code accordingly. The image below shows the port and number for each pin:
![image](https://user-images.githubusercontent.com/466120/46096980-eedad300-c1c0-11e8-95f2-2dfa35d31120.png)

**Comment by misan** [comment]
CHANGE=RISING+FALLING

more details https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/

You can select HIGH instead and use it for the STEP input.
