### ISSUE TITLE
Using lpd3806-600bm

### ISSUE THREAD

**Issue by PaulRobert1** [misan/dcservo#56]
Hello misan,

Is it possible to use a lpd3806 rotary encoder with your code?

Thank you.

**Comment by misan** [comment]
Sure, no problem other than the coupling with the motor.

**Comment by PaulRobert1** [comment]
Couse i did and the motor goes crazy like it would not detect it, tried switching a with b, mayb raise voltage? In the datasheet it states 5-30 vdc 
You are a patient man! :)))

**Comment by PaulRobert1** [comment]
I powered it from the arduino internal 5v stabiliser

**Comment by misan** [comment]
@PaulRobert1 What you need to be sure is the input pull-ups are enabled as the outputs of the encoder are open-collector according to this tear-down https://wemakethings.net/2014/05/26/rotary-encoder-teardown/

Or you just place a 4k7 resistor on each encoder input.

**Comment by PaulRobert1** [comment]
Gonna do that, thank u :))

**Comment by misan** [comment]
If you are using it with Marlin that sounds like an endstop problem.

**Comment by PaulRobert1** [comment]
I am using it with LinuxCNC.

**Comment by misan** [comment]
Not sure about it: Controller should honor Direction pin. If it does not,
on a single controller, I would double check the signal is, in fact,
changing value and, if that is the case, verify wiring.

If all looks ok, I would check the controller in stand-alone mode (use
serial comamnds to check motor moves in the two directions). If all works
ok then I would check if direction pin in Arduino might have been damaged
(does it still can read a proper digital value on than pi, both low and
high values?).

**Comment by PaulRobert1** [comment]
Problem was faulty wiring on the x dir input pin, all working as should.

Thank you!
